### ISSUE TITLE
Sobre as variáveis

### ISSUE THREAD

**Issue by Pereira-Araujo** [mxlock/jogo-da-velha#1]
Fala mano beleza? 
Então seu projeto ficou massa, mas assim, mas uma dica: tenta usar let e const ao invés de 'var', pq seu código fica mais moderno e usar 'var' já não é uma boa prática.

**Comment by mxlock** [comment]
Muito obrigado pela informação, já é algo que irei guardar comigo a partir de agora!

**Comment by Pereira-Araujo** [comment]
Show mano sucesso brother!
Obs.: Vi também que seu projeto não tem ReadMe... Faz toda a diferença ter um ReadMe com prints e informações sobre o seu código e tal, e ainda mais se for um projeto Front-End...
Tem umas diquinhas nesse artigo:
https://blog.rocketseat.com.br/como-fazer-um-bom-readme/
